baseURL = "https://john123797.github.io/"
languageCode = "zh-tw"
title = "大叔筆記"
theme = "m10c"
disqusShortname = "uncle-notes"

# Google Analytics UA number
googleAnalytics = "UA-79596126-6"

[menu]
  [[menu.main]]
    identifier = "home"
    weight = 10
    name = "首頁"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    weight = 20
    name = "標籤"
    url = "/tags/"

  [[menu.main]]
    identifier = "categories"
    weight = 30
    name = "分類"
    url = "/categories/"

  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about_me/"

[params]
  author = "Chung-Hsiang Cheng"
  description = "一個在邊緣角落的小小工程師"
  menu_item_separator = " "
  [[params.social]]
    name = "email"
    url = "mailto:john456797@gmail.com"
  [[params.social]]
    name = "github"
    url = "https://github.com/john123797"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/john123797"