baseURL = "https://john123797.github.io/"
languageCode = "zh-tw"
title = "大叔筆記"
theme = "m10c"

# Google Analytics UA number
googleAnalytics = "G-FNJ53MVHMH"

[menu]
  [[menu.main]]
    identifier = "home"
    weight = 10
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    weight = 20
    name = "Tags"
    url = "/tags/"

  [[menu.main]]
    identifier = "categories"
    name = "分類"
    url = "/categories/"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"



[params]
  author = "Chung-Hsiang Cheng"
  description = ""
  menu_item_separator = " "